### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [98mxr/GMFSS_union#5]
What is the difference between the two models: `prototype_wgan` and `prototype_vanillagan`?

**Comment by 98mxr** [comment]
The two models are slightly different in training, vanillagan uses GAN Type=gan and wgan has GAN Type=wgan.
We now believe that in practice prototype_vanillagan can produce a slight blur to counteract erroneous textures without losing the overall sharpness, while prototype_wgan is more sharp in all frames.
I'm told that prototype_wgan has some slight color variations in some scenes due to some mistakes I made when training wgan, but this doesn't seem to be a serious problem.

**Comment by jreoka** [comment]
Gotcha. Thank you so much for the info!!!

**Comment by jreoka** [comment]
Id say this has been completed!
